# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Todo App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Todo App
  pod 'RealmSwift', '~>10'
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  
  target 'Todo AppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
